#!/bin/bash
: 'Author:     Pixailz'
: 'created:    20/10/2022 13:49:43'
: 'updated:    27/10/2022 07:07:36'

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> PARTS

function	basic_part()
{
	echo_log_part "part" "basic"
	exec_module "perm"
	exec_module "parsing"
	exec_module "pipe"
	exec_module "redirection"
}

function	built_part()
{
	echo_log_part "part" "builtin"
	exec_module "builtin_cd"
	exec_module "builtin_exit"
}

function	exec_modules()
{
	if [ ${HAVE_MODULE} == 1 ]; then
		for module in ${DO_MODULE[*]}; do
			exec_module ${module}
		done
	else
		for part in ${DO_PART[*]}; do
			${part}_part
		done
	fi
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> MAIN

function	prepare_test()
{
	reset_deepfile
	clean_test
	# create a dir test
	mkdir test
}

function	clean_test()
{
	# if directory or file test exists remove it
	[ -d test ] || [ -f test ] && rm -rf test
}

function	main_entry()
{
	prepare_test
	install_modules
	exec_modules
	clean_test
}

function	get_cwd()
{
	local	mode=${1}

	if [ ${mode} == 1 ]; then
		local	base=${0}
	else
		local	base=${BASH_SOURCE[0]}
	fi

	CURRENT_DIR=$(dirname ${base})

	[ "${DEBUG}" == 1 ] && printf "current_dir : [%s]\n" ${CURRENT_DIR}
	[ "${DEBUG}" == 1 ] && printf "mode : [%s]\n" ${mode}
}

get_cwd 1

DIR_BASE=${CURRENT_DIR}
PATH_CONFIG=${DIR_BASE}/.config
[ "${DEBUG}" == 1 ] && printf "path_config [%s]\n" ${PATH_CONFIG}
source ${PATH_CONFIG}

parse_arg ${@}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	main_entry
fi

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
