#!/bin/bash

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> BASH COLOR

UL="\xe2\x95\x94"
HO="\xe2\x95\x90"
UR="\xe2\x95\x97"
VE="\xe2\x95\x91"
LL="\xe2\x95\x9a"
LR="\xe2\x95\x9d"

function	p_toggle_color()
{
	local	surrounding_mode="${1:-1}"
	local	end_esc=""

	if [ "${surrounding_mode}" == "1" ]; then
		BEG_ESC='\001'
		END_ESC='\002'
	else
		BEG_ESC=''
		END_ESC=''
	fi

	green="${BEG_ESC}\e[38;5;82m${END_ESC}"
	red="${BEG_ESC}\e[38;5;196m${END_ESC}"
	yellow="${BEG_ESC}\e[33m${END_ESC}"
	blue="${BEG_ESC}\e[38;5;75m${END_ESC}"
	orange="${BEG_ESC}\e[38;5;214m${END_ESC}"
	lgreen="${BEG_ESC}\e[92m${END_ESC}"
	lyellow="${BEG_ESC}\e[93m${END_ESC}"
	lblue="${BEG_ESC}\e[94m${END_ESC}"
	lmagenta="${BEG_ESC}\e[95m${END_ESC}"
	lcyan="${BEG_ESC}\e[96m${END_ESC}"

	blink="${BEG_ESC}\e[05m${END_ESC}"
	blink_red="${BEG_ESC}${blink}${red}${END_ESC}"
	restore="${BEG_ESC}\033[0m${END_ESC}"
	reset="${BEG_ESC}\e[0m${END_ESC}"

	P_INFO="${lcyan}[INFO]${reset}"
	P_WARN="${orange}[WARN]${reset}"
	P_QUES="${blue}[QUE?]${reset}"
	P_PASS="${green}[PASS]${reset}"
	P_FAIL="${red}[FAIL]${reset}"
	P_ERRO="${red}[ERRO]${reset}"
	SUCCESS="[${green}+${reset}] "
	FAILED="[${red}-${reset}] "
	INFO="[${blue}*${reset}] "
	WARN="[${orange}*${reset}] "

	DEEP_SEC_COLOR="${!LOG_TITLE_DEFAULT_COLOR}"
}

function	p_remove_colors()
{
	green=""
	red=""
	yellow=""
	blue=""
	orange=""
	lgreen=""
	lyellow=""
	lblue=""
	lmagenta=""
	lcyan=""
	blink=""
	blink_red=""
	restore=""
	reset=""
	SUCCESS="[+] "
	FAILED="[-] "
	INFO="[*] "
	WARN="[*] "
	P_INFO="[INFO]"
	P_WARN="[WARN]"
	P_QUES="[QUE?]"
	P_PASS="[PASS]"
	P_FAIL="[FAIL]"
	P_ERRO="[ERRO]"
	DEEP_SEC_COLOR=""
}

# print function

## print information
function	p_info()
{
	printf "%b %b%b\n" "${P_INFO}" "${1}" "${reset}"
}

## print warn
function	p_warn()
{
	printf "%b %b%b\n" "${P_WARN}" "${1}" "${reset}"
}

## print question
function	p_ques()
{
	if [ "${2}" == 1 ]; then
		printf "%b %b%b\b" "${P_QUES}" "${1}" "${reset}"
	else
		printf "%b %b%b\n" "${P_QUES}" "${1}" "${reset}"
	fi
}

## print success or not
function	p_pass() {
	if [ -z ${2} ] || [ ${2} == 0 ]; then
		printf "%b %b%b\n" "${P_PASS}" "${1}" "${reset}"
	else
		printf "%b %b%b\n" "${P_PASS}" "${1}" "${reset}"
	fi
}

## print error and quit
function	p_erro()
{
	printf "%b %b%b\n" "${P_ERRO}" "${1}" "${reset}"
	exit
}

## print parsing error and tips for calling help, then exit
function	p_error_parse()
{
	printf "%s : %b\n" "${SCRIPT_NAME}" "${1}"
	printf "Try '%s --help' for more information.\n" "${SCRIPT_NAME}"
	exit
}

## print pause and wait
function	p_pause()
{
	p_info "Press [Enter] to continue.."
	read readEnterkey
}

## print no such file or directory
function	p_no_such()
{
	p_warn "no such file or directory (${orange}${file_path}${reset})."
}
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
