#!/bin/bash

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> echo deep

function	echo_log_section()
{
	local	msg
	msg="$(echo -e "${1}" | sed -E "s/\\e\\[.*m//")"

	vertical_offset=$(printf "%0.s${HO}" $(seq 3 ${TITLE_LENGTH}))
	center_off=$(( ${TITLE_LENGTH} - ${#msg}))
	center_splited=$(( (${center_off} - 2) / 2 ))
	if [ $(( ${center_off} % 2)) == 0 ]; then
		CL=$(printf "%0.s " $(seq 1 ${center_splited}))
		CR=$(printf "%0.s " $(seq 1 ${center_splited}))
	else
		CL=$(printf "%0.s " $(seq 1 ${center_splited}))
		CR=$(printf "%0.s " $(seq 1 ${center_splited}) 1)
	fi
	if [ "${2}" == "1" ]; then
		printf "${DEEP_SEC_COLOR}${UL}${vertical_offset}${UR}\n" >> ${DEEPTHOUGHT_FILE}
		printf "${VE}${CL}${reset}${1}${DEEP_SEC_COLOR}${CR}${VE}\n" >> ${DEEPTHOUGHT_FILE}
		printf "${LL}${vertical_offset}${LR}${reset}\n" >> ${DEEPTHOUGHT_FILE}
	fi
	printf "${DEEP_SEC_COLOR}${UL}${vertical_offset}${UR}\n"
	printf "${VE}${CL}${reset}${1}${DEEP_SEC_COLOR}${CR}${VE}\n"
	printf "${LL}${vertical_offset}${LR}${reset}\n"
}

function	echo_log()
{
	local	offset=${1}
	local	mode=${2}
	local	msg=${3}
	local	print_out=${4}
	local	first_part=""
	local	offset_tab=""

	while [ ${offset} != 0 ]; do
		offset_tab="${offset_tab}${PRINT_LOG_OFFSET_STR}"
		offset=$((${offset} - 1))
	done
	if [ ${mode} == -1 ]; then
		first_part="${msg}"
	elif [ ${mode} == 0 ]; then
		first_part="${FAILED}${msg}"
	elif [ ${mode} == 1 ]; then
		first_part="${SUCCESS}${msg}"
	elif [ ${mode} == 2 ]; then
		first_part="${INFO}${msg}"
	elif [ ${mode} == 3 ]; then
		first_part="${WARN}${msg}"
	fi
	msg=$(printf "%s" "${first_part}" | sed "s|^|${offset_tab}|")
	if [ "${print_out}" == 1 ]; then
		printf "${msg}\n"
	fi
	printf "${msg}\n" >> ${DEEPTHOUGHT_FILE}
}

function	echo_log_new_line()
{
	echo_log 0 -1 "" 1
}

function	reset_deepfile()
{
	[ -f ${DEEPTHOUGHT_FILE} ] && rm -f ${DEEPTHOUGHT_FILE}
	echo_log_section "MINISHELL tester (${orange}pix${reset})." 1
}

function	echo_log_part() {
	local	part_str=${orange}${1}${reset}
	local	part_name=${2}

	DEEP_PART_NAME=${part_name}
	echo_log_new_line
	echo_log 0 3 "${blue}${part_name}${reset} ${part_str}" 1
}

function	echo_log_sect()
{
	local	sect_name=${1}
	local	part_name=${blue}${DEEP_PART_NAME}${reset}

	echo_log_new_line
	echo_log 1 2 "${part_name} ${sect_name}" 1
}

function	echo_log_current_cmd()
{
	local	mode=${1}
	local	curr_cmd=(${*})
	local	to_print_cmd=()
	local	to_print_str=""

	for item in ${curr_cmd[*]:1}; do
		if [ -f ${item} ] || [ -d ${item} ]; then
			# printf "file : %s\n" "${item}"
			if [ "${to_print_str}" == "" ]; then
				to_print_str="${item/${DIR_BASE}/.}"
			else
				to_print_str="${to_print_str} ${item/${DIR_BASE}/.}"
			fi
		else
			# printf "item : %s\n" "${item}"
			if [ "${to_print_str}" == "" ]; then
				to_print_str="${item}"
			else
				to_print_str="${to_print_str} ${item}"
			fi
		fi
	done
	echo_log 2 3 "\`${blue}${to_print_str}${reset}'" ${mode}
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
