#!/bin/bash

function	pre_exec_redirection()
{
	echo_deep_sect "redirection"
	TMP_DIR_USER=${DIR_BASE}/test/expect_user
	[ -d ${TMP_DIR_USER} ] || [ -f ${TMP_DIR_USER} ] && rm -rf ${TMP_DIR_USER}
	mkdir -p ${TMP_DIR_USER}
	TMP_DIR_BASH=${DIR_BASE}/test/expect_bash
	[ -d ${TMP_DIR_BASH} ] || [ -f ${TMP_DIR_BASH} ] && rm -rf ${TMP_DIR_BASH}
	mkdir -p ${TMP_DIR_BASH}
	for n in {01..12}; do
		TMP_FILE+=(file_${n})
		TMP_FILE_USER+=(${TMP_DIR_USER/${DIR_BASE}\//}/${TMP_FILE[${#TMP_FILE[@]} - 1]})
		TMP_FILE_BASH+=(${TMP_DIR_BASH/${DIR_BASE}\//}/${TMP_FILE[${#TMP_FILE[@]} - 1]})
		TMP_FILE_REPL+=($(cat /dev/urandom | xxd -p -l 3 -g 8))
	done
	exec_mode=3
	EXEC_DISABLE_DIFF=1
	return 0
}

function	exec_redirection()
{
	exec_command "echo pass > ${TMP_FILE_REPL[0]}"
	exec_command "\
echo pass1 > ${TMP_FILE_REPL[0]} | \
echo pass2 > ${TMP_FILE_REPL[1]} | \
echo pass3 > ${TMP_FILE_REPL[2]} | \
echo pass4 > ${TMP_FILE_REPL[3]}"
	exec_command "\
${TMP_FILE_REPL[0]} < echo pass1 > ${TMP_FILE_REPL[4]} | \
${TMP_FILE_REPL[1]} < echo pass2 > ${TMP_FILE_REPL[5]} | \
${TMP_FILE_REPL[2]} < echo pass3 > ${TMP_FILE_REPL[6]} | \
${TMP_FILE_REPL[3]} < echo pass4 > ${TMP_FILE_REPL[7]}"
	exec_command "\
${TMP_FILE_REPL[0]} < echo pass1 > ${TMP_FILE_REPL[4]} >> ${TMP_FILE_REPL[8]} | \
${TMP_FILE_REPL[1]} < echo pass2 > ${TMP_FILE_REPL[5]} >> ${TMP_FILE_REPL[9]} | \
${TMP_FILE_REPL[2]} < echo pass3 > ${TMP_FILE_REPL[6]} >> ${TMP_FILE_REPL[10]} | \
${TMP_FILE_REPL[3]} < echo pass4 > ${TMP_FILE_REPL[7]} >> ${TMP_FILE_REPL[11]}"
	return 0
}

function	post_exec_redirection()
{
	EXEC_DISABLE_DIFF=0
	exec_mode=0
	return 0
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "run" ]; then
		source ../../run
	elif [ "${0}" -ef "redirection/run" ]; then
		source ../run
	else
		source ./run
	fi
	pre_exec_redirection
	exec_redirection
fi
