#!/bin/bash

function	permission_exec_setup_create_file()
{
	local	permissions=${1}
	local	file_path=${2}

	[ -f ${file_path} ] || [ -d ${file_path} ] && rm -rf ${file_path}
	echo "echo pass" > ${file_path}
	chmod ${permissions} ${file_path}
}

function	pre_exec_perm()
{
	echo_log_sect "permission"
	mkdir ${TEST_DIR}/exec
	# me: ---, groups: ---, others: --- (false)
	permission_exec_setup_create_file 000 ${TEST_DIR}/exec/exec_00
	# me: --x, groups: ---, others: --- (false)
	permission_exec_setup_create_file 100 ${TEST_DIR}/exec/exec_01
	# me: -w-, groups: ---, others: --- (false)
	permission_exec_setup_create_file 200 ${TEST_DIR}/exec/exec_02
	# me: -wx, groups: ---, others: --- (false)
	permission_exec_setup_create_file 300 ${TEST_DIR}/exec/exec_03
	# me: r--, groups: ---, others: --- (false)
	permission_exec_setup_create_file 400 ${TEST_DIR}/exec/exec_04
	# me: r-x, groups: ---, others: --- (true)
	permission_exec_setup_create_file 500 ${TEST_DIR}/exec/exec_05
	# me: rw-, groups: ---, others: --- (false)
	permission_exec_setup_create_file 600 ${TEST_DIR}/exec/exec_06
	# me: rwx, groups: ---, others: --- (true)
	permission_exec_setup_create_file 700 ${TEST_DIR}/exec/exec_07
	EXEC_MODE=1
	return 0
}

function	exec_perm()
{
	exec_command "${TEST_DIR}/exec/exec_00" 3 3
	exec_command "${TEST_DIR}/exec/exec_01" 3 3
	exec_command "${TEST_DIR}/exec/exec_02" 3 3
	exec_command "${TEST_DIR}/exec/exec_03" 3 3
	exec_command "${TEST_DIR}/exec/exec_04" 3 3
	exec_command "${TEST_DIR}/exec/exec_06" 3 3
	exec_command "${TEST_DIR}/exec/exec_05"
	exec_command "${TEST_DIR}/exec/exec_07"
	return 0
}

function post_exec_perm()
{
	EXEC_MODE=0
	return 0
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "run" ]; then
		source ../../run
	elif [ "${0}" -ef "perm/run" ]; then
		source ../run
	else
		source ./run
	fi
	pre_exec_perm
	exec_perm
	post_exec_perm
fi
