#!/bin/bash

function	pre_exec_parsing()
{
	echo_log_sect "parsing"
	TMP_FILE=./${TEST_DIR}/file
	echo Seekers > ${TMP_FILE}
	return 0
}

function	exec_parsing()
{
	exec_command "ca't' -e ${TMP_FILE}"
	exec_command "ca't -e' \"${TMP_FILE}\""
	exec_command "cat -e \"test/'fi'le\""
	exec_command "cat -e \"test/'fi'\"le\"\""
	return 0
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "run" ]; then
		source ../../run
	elif [ "${0}" -ef "parsing/run" ]; then
		source ../run
	else
		source ./run
	fi
	pre_exec_parsing
	exec_parsing
fi
