#!/bin/bash

function	post_exec_module()
{
	local	last_return=${1}
	local	function_name=${2}
	local	begin_color=""

	if [ ${DEBUG} ] && [ ${last_return} == 1 ]; then
		if [ ${RETURN_VALUE} == 0 ]; then
			return_value="[ ${green}0${reset} ]"
		elif [ ${RETURN_VALUE} -lt 10 ]; then
	 		return_value="[ ${red}${RETURN_VALUE}${reset} ]"
		elif [ ${RETURN_VALUE} -lt 100 ]; then
			return_value="[ ${red}${RETURN_VALUE}${reset}]"
		else
			return_value="[${red}${RETURN_VALUE}${reset}]"
		fi
		p_pass "${return_value} return from ${orange}${function_name}${reset}" ${RETURN_VALUE}
	fi
}

function	exec_module()
{
	local	module_name=${1}
	last_return=""

	for prefix in ${PREFIX_ENTRY_MODULE_EXEC[*]}; do
		if_function_do "${prefix}${module_name}"
		post_exec_module ${?} "${prefix}${module_name}"
	done

	return ${RETURN_VALUE}
}
